<?php

namespace AppBundle\Repository;

/**
 * AddressClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressClientRepository extends \Doctrine\ORM\EntityRepository
{
}
