<?php

namespace AppBundle\Repository;

/**
 * AddressUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressUserRepository extends \Doctrine\ORM\EntityRepository
{
}
