<?php

namespace AppBundle\Repository;

/**
 * ConceptMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
