<?php

namespace AppBundle\Repository;

/**
 * ConceptProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptProductRepository extends \Doctrine\ORM\EntityRepository
{
}
