<?php

namespace AppBundle\Repository;

/**
 * ConceptStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
