<?php

namespace AppBundle\Repository;

/**
 * ConceptMediaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptMediaTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
