<?php

namespace AppBundle\Repository;

/**
 * OrderStatusLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatusLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
