<?php

namespace AppBundle\Repository;

/**
 * ProductMediaTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMediaTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
