<?php

namespace AppBundle\Repository;

/**
 * ProductMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
