<?php

namespace AppBundle\Repository;

/**
 * SupplierStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
