<?php

namespace AppBundle\Repository;

/**
 * SupplierProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierProductRepository extends \Doctrine\ORM\EntityRepository
{
}
